name: Deploy to Staging

on:
  push:
    branches:
      - staging

permissions:
  contents: read

jobs:
  deployer:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v4

      - name: Install Deployer CLI
        run: |
          curl -LO https://deployer.org/deployer.phar
          mv deployer.phar /usr/local/bin/dep
          chmod +x /usr/local/bin/dep

      - name: Deploy
        run: dep deploy test
